### PR TITLE
scripts: add Prefetch.hs

### PR DESCRIPTION
**Pull request by Profpatsch**
To run:

```
$ nix-shell --pure --run "runhaskell scripts/Prefetch.hs" \
    | tee hashes.json
```

Prefetch.hs is an experiment of calling directly into the Dhall
library to read spacchetti. Dhall has no concept of a map of values
with uniform type, so we match into the syntax tree manually and then
check each package.

It will use libnix to prefetch the git repositories and output a json
of hashes. The prefetching clones five repositories at a time and
retries on network errors.

@justinwoo this made me notice that the your `unordered-collections` patch can’t be fetched any more.

### CODE REVIEW

**Comment by justinwoo** [comment]
hm, the git branch is still there and all, but i guess i'll update it

**Comment by justinwoo** [comment]
updated in 6ba1006 updated unordered-collections

**Comment by justinwoo** [comment]
Btw, could you move that old nix shell file into a separate one? I still want to use it~

**Comment by Profpatsch** [comment]
> Btw, could you move that old nix shell file into a separate one? I still want to use it~

The new one should be a superset of the old; of course it has a few more dependencies. We can factor it out if you want to, so that it’s possible to open a smaller shell with e.g. `nix-shell -A small` (or the other way around if you prefer).

**Comment by justinwoo** [comment]
That sounds good

**Comment by justinwoo** [comment]
Should we merge this sooner or later?

**Comment by Profpatsch** [comment]
I want to update the `shell.nix` first, didn’t have the time yesterday.

**Comment by xcthulhu** [comment]
I can't get this to work. Here's what I tried:

```
$ cd /tmp
$ git clone git@github.com:Profpatsch/spacchetti.git
$ cd spacchetti
$ nix-shell --pure --run "runhaskell scripts/Prefetch.hs"
error: cannot coerce null to a string, at /tmp/spacchetti/spacchetti/shell.nix:67:21
```

Does this command need an argument?

**Comment by Profpatsch** [comment]
> $ git clone git@github.com:Profpatsch/spacchetti.git

You need to check out the `haskell-prefetch-sha` branch.

**Comment by xcthulhu** [comment]
Okay, I  managed to get around the `error: cannot coerce null to a string` bug by getting rid of these two lines in `shell.nix`:

```
# TODO: remove once https://github.com/dhall-lang/dhall-haskell/issues/504 is fixed
LOCALE_ARCHIVE = "${glibcLocales}/lib/locale/locale-archive";
```

Now I am getting this:

```
$ nix-shell --pure --run "runhaskell scripts/Prefetch.hs"
Fetching repo for web-storage (retry 0)
Fetching repo for bigints (retry 0)
Fetching repo for node-fs-aff (retry 0)
...
Fetching repo for unordered-collections (retry 0)
...
Fetching repo for unordered-collections (retry 1)
...
Fetching repo for unordered-collections (retry 5)
...
Fetching repo for milkis (retry 0)
UnknownPrefetchError
Initialized empty Git repository in /private/var/folders/fd/z1w7mk8n3tlc2slqmwhp8ngh0000gn/T/git-checkout-tmp-DcCUIpKN/purescript-unordered-collections/.git/
fatal: Couldn't find remote ref refs/tags/missing-deps
From https://github.com/justinwoo/purescript-unordered-collections
 * [new branch]      champjs                -> origin/champjs
 * [new branch]      master                 -> origin/master
 * [new branch]      missing-deps           -> origin/missing-deps
 * [new branch]      mostly-pure-purescript -> origin/mostly-pure-purescript
 * [new tag]         v0.1.0                 -> v0.1.0
 * [new tag]         v0.2.0                 -> v0.2.0
 * [new tag]         v1.0.0                 -> v1.0.0
 * [new tag]         v1.0.1                 -> v1.0.1
 * [new tag]         v1.1.0                 -> v1.1.0
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
Unable to checkout refs/tags/missing-deps from https://github.com/justinwoo/purescript-unordered-collections.git.
```

Any ideas?

**Comment by Profpatsch** [comment]
> Any ideas?

Yeah, the first few comments in this PR. :)

> I managed to get around the error: cannot coerce null to a string bug by getting rid of these two lines in shell.nix:

Ah, you’re probably on an older `nixpkgs` checkout, I recommend a current `unstable`.

**Comment by xcthulhu** [comment]
>> Any ideas?

> Yeah, the first few comments in this PR. :)

Okay, now I see what you mean by this comment 

>@justinwoo this made me notice that the your unordered-collections patch can’t be fetched any more.

--------------

> Ah, you’re probably on an older nixpkgs checkout, I recommend a current unstable.

Are you sure?  Here's what I've tried at the console:

```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
$ nix-channel --update
unpacking channels...
created 2 symlinks in user environment
$ nix-shell --pure --run "runhaskell scripts/Prefetch.hs"
error: cannot coerce null to a string, at .../shell.nix:67:21
(use '--show-trace' to show detailed location information)
```

This is on my MacBook. 

I just tried on my linux box I don't get this issue... :(

**Comment by Profpatsch** [comment]
> This is on my MacBook.

Duh, of course you’ll run into strange issues on Darwin. Always mention that you are on MacOS with nixpkgs. People still caring for Apple’s stuff have to special-case a lot of nixpkgs and apparently some still think that `null`ing out packages is a good idea.

**Comment by xcthulhu** [comment]
>> I am still falling over on @justinwoo's unordered-collections and not seeing the hashes.

> Have you applied the mentioned patch then?

Okay, now I have.

With `LOCALE_ARCHIVE = "${glibcLocales}/lib/locale/locale-archive";` commented out this works fine on the mac (I'll try on linux in a little bit, still trying version pinning).

**Comment by Profpatsch** [comment]
Okay, I’ve added a smaller nix shell, you can invoke it with `nix-shell -A small`. cc @justinwoo

**Comment by Profpatsch** [comment]
I’ve fixed the problem with `glibcLocales` on Darwin and added two small sections to the README.

**Pull request merged**
